### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by wouter-swierstra** [VictorCMiraldo/hs-digems#5]
https://github.com/VictorCMiraldo/hs-digems/blob/64f9c30d67962812c9add57d355e5bad1d3d940f/writeup/src/body.lhs#L32

I'm not sure what you mean with this sentence? It seems a bit backwards to say 'two parts of the program changed on the same line' is a single change -- can't you make a stronger case if you talk about 'each change to a program modifies the entire line on which it lives' -- this is fine for some changes, but bad for many common refactorings such as variable rename?

**Comment by VictorCMiraldo** [comment]
It is very dangerous to mention `variable renaming` that early. This might give the impression we will handle binders but we don't. Maybe something like:

```
thereby enabling, for
example, two changes that work on separate parts of the AST
to be trivially merged, even if they appear to be on the same line in the source file. 
```

**Comment by wouter-swierstra** [comment]
Sure.
